apiVersion: v1
description: A Helm chart for knative build pipeline
name: tekton
version: 0.0.1-SNAPSHOT
icon: https://raw.githubusercontent.com/knative/docs/1acad47/images/logo/rgb/knative-logo-rgb.png