image:
  upstreamtag: v20190308-186ac3b6
  kubeconfigwriter: gcr.io/abayer-jx-experiment/kubeconfigwriter
  credsinit: gcr.io/abayer-jx-experiment/creds-init
  gitinit: gcr.io/abayer-jx-experiment/git-init
  nop: gcr.io/abayer-jx-experiment/nop
  bash: gcr.io/abayer-jx-experiment/bash
  gsutil: gcr.io/abayer-jx-experiment/gsutil
  controller: gcr.io/abayer-jx-experiment/controller
  webhook: gcr.io/abayer-jx-experiment/webhook
auth:
  git:
    username:
    password:
    url: https://github.com
  docker:
    username:
    password:
    url: https://index.docker.io/v1/
    # url: https://gcr.io

webhook:
  enabled: true

rbac:
  cluster: true