image:
  upstreamtag: v20191226-3b2fe236a
  kubeconfigwriter: gcr.io/abayer-pipeline-crd/kubeconfigwriter
  credsinit: gcr.io/abayer-pipeline-crd/creds-init
  gitinit: gcr.io/abayer-pipeline-crd/git-init
  nop: gcr.io/abayer-pipeline-crd/nop
  bash: gcr.io/abayer-pipeline-crd/bash
  gsutil: gcr.io/abayer-pipeline-crd/gsutil
  controller: gcr.io/abayer-pipeline-crd/controller
  webhook: gcr.io/abayer-pipeline-crd/webhook
  entrypoint: gcr.io/abayer-pipeline-crd/entrypoint
  pullrequest: gcr.io/abayer-pipeline-crd/pullrequest-init
  imagedigestexporter: gcr.io/abayer-pipeline-crd/imagedigestexporter
  gcsfetcher: gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.8.0
auth:
  git:
    username:
    password:
    url: https://github.com
  docker:
    username:
    password:
    url: https://index.docker.io/v1/
    # url: https://gcr.io

webhook:
  enabled: true

rbac:
  cluster: true

pvc:
  size: 5Gi
