{{- if .Values.auth.git.username }}
apiVersion: v1
data:
  password: {{ .Values.auth.git.password | b64enc | quote }}
  username: {{ .Values.auth.git.username | b64enc | quote }}
kind: Secret
metadata:
  name: knative-git-user-pass
  annotations:
    tekton.dev/git-0: {{ .Values.auth.git.url | quote }}
type: kubernetes.io/basic-auth
{{- end }}