{{- if .Values.pipeline.auth.docker.username }}
apiVersion: v1
data:
  password: {{ .Values.pipeline.auth.docker.password | b64enc | quote }}
  username: {{ .Values.pipeline.auth.docker.username | b64enc | quote }}
kind: Secret
metadata:
  name: knative-docker-user-pass
  annotations:
    build.knative.dev/docker-0: username: {{ .Values.pipeline.auth.docker.url | quote }}
type: kubernetes.io/basic-auth
{{- end }}