apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jx-knative-pipeline-bot-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-build-bot
subjects:
- kind: ServiceAccount
  name: {{ template "pipeline.name" . }}
  namespace: {{ .Release.Namespace }}
