apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "build-bot.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "build-bot.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "build-bot.name" . }}