# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "pipeline.name" . }}-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "pipeline.name" . }}-controller
    spec:
      serviceAccountName: {{ template "pipeline.name" . }}
      containers:
      - name: {{ template "pipeline.name" . }}
        #image: {{ .Values.image.controller }}:{{ .Values.image.upstreamtag }}
        image: gcr.io/jenkinsx-dev/controller-7cb61323de6451022678822f2a2d2291@sha256:dc164f2ef0f334516a12e01838bb00916fe1b699ac169dcf77045a8b55ec6a5b
        args: [
          "-logtostderr",
          "-stderrthreshold", "INFO",
          "-kubeconfig-writer-image", "{{ .Values.image.kubeconfigwriter }}:{{ .Values.image.upstreamtag }}",
          "-creds-image", "{{ .Values.image.credsinit }}:{{ .Values.image.upstreamtag }}",
          "-git-image", "{{ .Values.image.gitinit }}:{{ .Values.image.upstreamtag }}",
          "-nop-image", "{{ .Values.image.nop }}:{{ .Values.image.upstreamtag }}",
          "-bash-noop-image", "{{ .Values.image.bash }}:{{ .Values.image.upstreamtag }}",
          "-gsutil-image", "{{ .Values.image.gsutil }}:{{ .Values.image.upstreamtag }}",
        ]
        env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
